/**
 * The container scaffolding for a synthetic browser monitor — PURE text
 * builders, NO `void/*` imports, so they are unit-testable and equally usable
 * from the `SandboxExecutor` (which `writeFile`s the output into the container)
 * without dragging the runtime in.
 *
 * The `SandboxExecutor` lays out a tiny throwaway Playwright project inside the
 * container:
 *   /work/playwright.config.ts   ← {@link generatePlaywrightConfig}
 *   /work/tests/<specFilename()> ← the user's `monitors.source` verbatim
 * then runs `npx playwright test`. The config registers `@wrightful/reporter`,
 * which — driven by the `WRIGHTFUL_*` env the executor sets (see the LINKING
 * design in the monitors notes) — opens a run with `idempotencyKey ===
 * execution.id`, `origin = "synthetic"`, and `monitorId` set, so the executor
 * can resolve the produced run back by `(projectId, idempotencyKey)`.
 *
 * The config is deliberately minimal and self-contained: single chromium
 * project, `workers: 1` (a monitor is one logical check, not a parallel suite —
 * serial keeps container CPU/memory bounded and the run's timeline legible),
 * and a per-test timeout sourced from `PLAYWRIGHT_TIMEOUT_MS` env so the
 * executor can clamp it to `WRIGHTFUL_MONITOR_MAX_DURATION_SECONDS` without
 * re-baking the file. The reporter URL/token/idempotency/origin/monitor inputs
 * are NOT inlined here — they flow through process env so this builder stays a
 * pure function of its one structural input (the reporter module specifier) and
 * the same config text works for every execution.
 */

/** Inputs for {@link generatePlaywrightConfig}. */
export interface GeneratePlaywrightConfigOptions {
  /**
   * Module specifier the generated config registers as its reporter — normally
   * `"@wrightful/reporter"` (resolved from the container's `node_modules`). A
   * parameter rather than a hardcode so a test can assert it lands in the
   * `reporter: [[ ... ]]` tuple and a future executor variant can point at a
   * vendored path without editing this module.
   */
  reporterModule: string;
}

/**
 * The single spec file the container runs. A monitor is exactly one
 * user-authored Playwright file, written verbatim to `/work/tests/<this>`; the
 * name is fixed (not derived from the monitor) so the config's `testDir` +
 * default glob always picks it up and nothing leaks the monitor's id/name into
 * the container filesystem. `.spec.ts` so Playwright's default `testMatch`
 * (`**\/*.@(spec|test).?(c|m)[jt]s?(x)`) selects it without extra config.
 */
export function specFilename(): string {
  return "check.spec.ts";
}

/**
 * Build the `playwright.config.ts` text the container runs. PURE — a function of
 * `reporterModule` only; every per-execution input (dashboard URL, token,
 * idempotency key, monitor id, run origin, timeout) is read from process env at
 * container runtime so the same config text is reused for every monitor
 * execution and this builder has no IO.
 *
 * Shape pinned by `playwright-config.test.ts`:
 *   - registers `@wrightful/reporter` (the `reporterModule`) — the reporter
 *     reads `WRIGHTFUL_URL` / `WRIGHTFUL_TOKEN` / `WRIGHTFUL_IDEMPOTENCY_KEY` /
 *     `WRIGHTFUL_MONITOR_ID` / `WRIGHTFUL_RUN_ORIGIN` from env itself, so they
 *     are NOT named here;
 *   - `workers: 1` and a single `chromium` project (one logical check, serial);
 *   - `retries: 0` (a monitor wants the true pass/fail of one attempt, not a
 *     flaky-masking retry);
 *   - per-test `timeout` from `PLAYWRIGHT_TIMEOUT_MS` env (the executor sets it
 *     from `WRIGHTFUL_MONITOR_MAX_DURATION_SECONDS`), defaulting to 30s when
 *     unset so a hand-run container still has a sane bound.
 */
export function generatePlaywrightConfig(
  opts: GeneratePlaywrightConfigOptions,
): string {
  return `import { defineConfig, devices } from "@playwright/test";

// Generated by the Wrightful synthetic-monitor executor. Do not edit by hand.
// The reporter reads the dashboard URL, token, idempotency key, monitor id, and
// run origin from the process environment the container was launched with, so
// it streams this run back to the dashboard linked to its monitor execution.
export default defineConfig({
  testDir: "./tests",
  workers: 1,
  retries: 0,
  fullyParallel: false,
  reporter: [["${opts.reporterModule}"]],
  timeout: Number(process.env.PLAYWRIGHT_TIMEOUT_MS) || 30000,
  use: {
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
  ],
});
`;
}
