// Kysely interface for the control D1 database.
//
// Timestamps are stored as INTEGER in SQLite and surfaced as `number` here —
// seconds-since-epoch for Wrightful app tables, milliseconds-since-epoch for
// Better Auth tables (following Better Auth's canonical column layout).
// Booleans are stored as INTEGER 0/1 and surfaced as `number`. Call sites do
// the narrow conversion (`Boolean(x)` / `new Date(x * 1000)`) where needed.

// ---------- Tenancy ----------

export interface TeamsTable {
  id: string;
  slug: string;
  name: string;
  /** Unix seconds */
  createdAt: number;
  /**
   * Unix seconds of the team's last ingest write. Nullable because newly
   * created teams haven't seen any runs yet. The watchdog reads this to
   * decide which tenant DOs to fan out to.
   */
  lastActivityAt: number | null;
  /**
   * GitHub organisation slug (lowercased). When set, any dashboard user
   * who is a member of this GitHub org will see the team as "available to
   * join" in their sidebar and profile page.
   */
  githubOrgSlug: string | null;
}

export interface ProjectsTable {
  id: string;
  teamId: string;
  slug: string;
  name: string;
  /** Unix seconds */
  createdAt: number;
}

export type MembershipRole = "owner" | "member";

export interface MembershipsTable {
  id: string;
  userId: string;
  teamId: string;
  role: MembershipRole;
  /** Unix seconds */
  createdAt: number;
}

export interface TeamInvitesTable {
  id: string;
  teamId: string;
  /** SHA-256 hex of the URL-safe random token. Plaintext is shown once at
   *  creation and never stored. */
  tokenHash: string;
  /** Role granted to accepting users. */
  role: MembershipRole;
  /** User who created the invite. */
  createdBy: string;
  /** Unix seconds */
  createdAt: number;
  /** Unix seconds after which the invite is no longer valid. */
  expiresAt: number;
}

export interface UserStateTable {
  userId: string;
  lastTeamId: string | null;
  lastProjectId: string | null;
  /** Unix milliseconds */
  updatedAt: number;
}

export interface TeamSuggestionDismissalsTable {
  userId: string;
  teamId: string;
  /** Unix seconds */
  dismissedAt: number;
}

export interface UserGithubOrgsTable {
  userId: string;
  /** JSON array of lowercased GitHub org slugs. Empty array = we know they're in no orgs. */
  orgSlugsJson: string;
  /** Unix seconds the cache was last refreshed. */
  refreshedAt: number;
  /** 0/1: whether the access token used for the last refresh carried the `read:org` scope. */
  scopeOk: number;
}

// ---------- API keys ----------

export interface ApiKeysTable {
  id: string;
  projectId: string;
  label: string;
  keyHash: string;
  keyPrefix: string;
  /** Unix seconds */
  createdAt: number;
  /** Unix seconds */
  lastUsedAt: number | null;
  /** Unix seconds */
  revokedAt: number | null;
}

// ---------- Better Auth core ----------
// Column names + types follow Better Auth's canonical SQLite layout so the
// kyselyAdapter resolves them by default. IDs are generated by our own
// `ulid()` via auth.advanced.database.generateId so they match project
// convention.

export interface UserTable {
  id: string;
  name: string;
  email: string;
  /** 0/1 */
  emailVerified: number;
  image: string | null;
  /** Unix milliseconds */
  createdAt: number;
  /** Unix milliseconds */
  updatedAt: number;
}

export interface SessionTable {
  id: string;
  /** Unix milliseconds */
  expiresAt: number;
  token: string;
  /** Unix milliseconds */
  createdAt: number;
  /** Unix milliseconds */
  updatedAt: number;
  ipAddress: string | null;
  userAgent: string | null;
  userId: string;
}

export interface AccountTable {
  id: string;
  accountId: string;
  providerId: string;
  userId: string;
  accessToken: string | null;
  refreshToken: string | null;
  idToken: string | null;
  /** Unix milliseconds */
  accessTokenExpiresAt: number | null;
  /** Unix milliseconds */
  refreshTokenExpiresAt: number | null;
  scope: string | null;
  password: string | null;
  /** Unix milliseconds */
  createdAt: number;
  /** Unix milliseconds */
  updatedAt: number;
}

export interface VerificationTable {
  id: string;
  identifier: string;
  value: string;
  /** Unix milliseconds */
  expiresAt: number;
  /** Unix milliseconds */
  createdAt: number;
  /** Unix milliseconds */
  updatedAt: number;
}

// CamelCasePlugin is installed on the Kysely instance (see `./index.ts`), so
// all keys here are camelCase — both table names and columns. The plugin
// converts them to snake_case in emitted SQL, matching the existing DB
// schema (`api_keys`, `user_state`, `user_id`, `created_at`, …).

export interface ControlDB {
  teams: TeamsTable;
  projects: ProjectsTable;
  memberships: MembershipsTable;
  teamInvites: TeamInvitesTable;
  teamSuggestionDismissals: TeamSuggestionDismissalsTable;
  userGithubOrgs: UserGithubOrgsTable;
  userState: UserStateTable;
  apiKeys: ApiKeysTable;
  user: UserTable;
  session: SessionTable;
  account: AccountTable;
  verification: VerificationTable;
}

export type DB = ControlDB;
