/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 3cd8c4fb722ef604e58b15e0406055c5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		R2: R2Bucket;
		DB: D1Database;
		AUTH_RATE_LIMITER: RateLimit;
		API_RATE_LIMITER: RateLimit;
		ARTIFACT_RATE_LIMITER: RateLimit;
		ASSETS: Fetcher;
		WRIGHTFUL_MAX_ARTIFACT_BYTES: "52428800";
		WRIGHTFUL_PUBLIC_URL: "http://localhost:5173";
		WRIGHTFUL_RUN_STALE_MINUTES: "30";
		BETTER_AUTH_SECRET: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WRIGHTFUL_MAX_ARTIFACT_BYTES" | "WRIGHTFUL_PUBLIC_URL" | "WRIGHTFUL_RUN_STALE_MINUTES" | "BETTER_AUTH_SECRET">> {}
}
