/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: f050a0f85c2401b5e075b902a409c731)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		R2: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		R2_ACCOUNT_ID: "";
		R2_BUCKET_NAME: "wrightful-artifacts";
		WRIGHTFUL_MAX_ARTIFACT_BYTES: "52428800";
		WRIGHTFUL_PRESIGN_PUT_TTL_SECONDS: "900";
		WRIGHTFUL_PRESIGN_GET_TTL_SECONDS: "600";
		WRIGHTFUL_PUBLIC_URL: "";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "WRIGHTFUL_MAX_ARTIFACT_BYTES" | "WRIGHTFUL_PRESIGN_PUT_TTL_SECONDS" | "WRIGHTFUL_PRESIGN_GET_TTL_SECONDS" | "WRIGHTFUL_PUBLIC_URL">> {}
}
