/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 2762ce42b85c3b332af0c10cf2d50e4a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		R2: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		R2_ACCOUNT_ID: "";
		R2_BUCKET_NAME: "greenroom-artifacts";
		GREENROOM_MAX_ARTIFACT_BYTES: "52428800";
		GREENROOM_PRESIGN_PUT_TTL_SECONDS: "900";
		GREENROOM_PRESIGN_GET_TTL_SECONDS: "600";
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "GREENROOM_MAX_ARTIFACT_BYTES" | "GREENROOM_PRESIGN_PUT_TTL_SECONDS" | "GREENROOM_PRESIGN_GET_TTL_SECONDS">> {}
}
