"use client";

import type { Dispatch, SetStateAction } from "react";
import { useRouter } from "@void/react";
import type { WebSocketRouteMap } from "void/routes";
import { requestReconnectRefresh } from "@/realtime/reconnect-refresh";
import { useRoom } from "@/realtime/use-room";
import { useSeededState } from "@/realtime/use-seeded-state";

/**
 * Route-map-derived helpers, mirroring `use-room.ts`. `WebSocketRouteMap`
 * (generated by `void prepare`) maps each room path to its `params` + `server`
 * event types, so a hook over `P` flows the exact params shape and server event
 * type with no per-room assertion.
 */
type RoomPath = keyof WebSocketRouteMap;
type ParamsOf<P extends RoomPath> = WebSocketRouteMap[P] extends {
  params: infer T;
}
  ? T
  : never;
type ServerEventOf<P extends RoomPath> = WebSocketRouteMap[P] extends {
  server: infer T;
}
  ? T
  : never;

/**
 * One path-generic "consume a `void/ws` room with no replay" hook — the React
 * plumbing shared by every feed consumer (`useProjectRoom`, `useRunRoom`, the
 * monitors roster). The pure reducers (`applyProjectFeedEvent` /
 * `applyRunProgressEvent` / `applyMonitorFeedEvent`) stay in their own homes;
 * this hook is only the wiring AROUND them, in one place:
 *
 *   1. Seed live state from SSR data via `useSeededState`, keyed on `seedDeps`.
 *      Void renders page components UNKEYED across SPA navigations, so
 *      navigating run A → run B (or changing list filters) re-renders the same
 *      mounted component with fresh loader props; when the seed identity changes
 *      during render the state resets from `seed()` before children re-render
 *      (no committed frame of stale state). Every dep must be referentially
 *      STABLE across re-renders of the same page instance — pass loader props
 *      through (or memoize derived objects on a loader prop).
 *
 *   2. Fold each server message through `fold` into the seeded setter. `fold` is
 *      read fresh each render by `useRoom` (closures re-bound via refs), so a
 *      reducer that closes over current view props — `acceptNewRuns` / `origin`
 *      on the runs list — always applies the live view without re-opening the
 *      socket. A reducer that returns the SAME state reference (e.g. an event it
 *      ignores) lets React bail out: no re-render, just the frame's parse cost.
 *
 *   3. On a WS RE-open after a drop (rooms have no event replay, so any
 *      broadcast missed while disconnected is gone) trigger `router.refresh()`:
 *      the loader re-runs and the reseed in step 1 folds the fresh props in.
 *      Coalesced via `requestReconnectRefresh` so the several leaves sharing a
 *      room's socket issue ONE refresh per reconnect burst, not one each.
 *
 * Returns the seeded state and its setter (`useState`-shaped). Read-only
 * consumers (`useProjectRoom` / `useRunRoom`) take just the state; the monitors
 * roster keeps the setter for its optimistic pause toggle, which writes the same
 * seeded list outside the feed.
 */
export function useFeedRoom<P extends RoomPath, S>(
  path: P,
  params: ParamsOf<P>,
  seedDeps: readonly unknown[],
  seed: () => S,
  fold: (prev: S, event: ServerEventOf<P>) => S,
): [S, Dispatch<SetStateAction<S>>] {
  const router = useRouter();

  const [state, setState] = useSeededState<S>(seedDeps, seed);

  useRoom(
    path,
    params,
    (event) => {
      setState((prev) => fold(prev, event));
    },
    () => {
      requestReconnectRefresh(() => router.refresh());
    },
  );

  return [state, setState];
}
