"use client";

import { useEffect, useRef } from "react";
import { connect, type ConnectCommonOptions, type VoidSocket } from "void/ws";
import type { WebSocketRouteMap } from "void/routes";

/**
 * Route-map-derived helpers. `WebSocketRouteMap` (generated by `void prepare`)
 * maps each room path to its `params` + `server` event types — the same source
 * Void's own `connect` is typed against — so a hook over `P` flows the exact
 * params shape and server event type to its caller with no per-room assertion.
 */
type RoomPath = keyof WebSocketRouteMap;
type ParamsOf<P extends RoomPath> = WebSocketRouteMap[P] extends {
  params: infer T;
}
  ? T
  : never;
type ServerEventOf<P extends RoomPath> = WebSocketRouteMap[P] extends {
  server: infer T;
}
  ? T
  : never;

/**
 * Void's `connect` is typed `connect<P>(path, options: ConnectOptions<P>)`, but
 * `ConnectOptions<P>` (a) isn't exported and (b) gates `params` behind a
 * `HasParams<P>` conditional that can't be resolved for a FREE generic `P`, so a
 * direct `connect(path, { params })` fails to type-check inside a generic
 * function. Alias it to its resolved-for-our-rooms shape (params always present)
 * — this PRESERVES the route-map typing (path `P`, `params: ParamsOf<P>`, and
 * `VoidSocket<P>` whose `on("message")` yields `ServerEventOf<P>`); it does NOT
 * erase to `string` / `Record<string,string>` / `unknown` like a lossy cast.
 */
// oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- aliases `connect` to its resolved-for-our-rooms shape; type-preserving, not lossy (see comment above)
const connectRoom = connect as unknown as <P extends RoomPath>(
  path: P,
  options: ConnectCommonOptions & { params: ParamsOf<P> },
) => VoidSocket<P>;

/**
 * Reconnect cadence. Void's VoidSocket auto-reconnects on every non-user close
 * at a flat 1s with no backoff and no cap; a tab whose session has expired
 * (the upgrade is rejected 403 in `onBeforeConnect`) would otherwise re-dial
 * once a second forever, waking the room DO each time. A few seconds softens
 * that storm while still recovering quickly from a transient blip. (Void exposes
 * only a flat delay, not exponential backoff.)
 */
const RECONNECT_DELAY_MS = 3000;

interface SharedRoom {
  close: () => void;
  /** Removes the message + open handlers the shared socket fans out through. */
  detach: () => void;
  listeners: Set<(event: unknown) => void>;
  /** Fired on every RE-open (reconnect after a drop), never the first open. */
  reconnectListeners: Set<() => void>;
  refCount: number;
}

/**
 * Module-level shared-connection registry, keyed by `path|params`. A run-detail
 * page mounts SEVERAL live leaves against the same room (status glyph, duration,
 * summary tiles, per-test list); the islands convention keeps each a separate
 * leaf (no client page-root provider to thread one subscription through).
 * Without sharing, each leaf would open its own WebSocket to the same Durable
 * Object: N handshakes + N connected clients for one tab. Ref-counted sharing
 * collapses them to ONE socket — opened on the first subscriber, fanned out to
 * all, closed when the last unmounts.
 */
const rooms = new Map<string, SharedRoom>();

/**
 * Subscribe `onEvent` to the room identified by (`path`, `params`); `key` is the
 * caller's stable `path|params` string. Returns an unsubscribe that drops the
 * listener and closes the underlying socket once no listener remains. Pure of
 * React so the ref-counting is unit-testable with a fake `connect`.
 *
 * `onReconnect` (optional) fires when the shared socket RE-opens after a drop
 * — never on the first open. Rooms have no event replay (a viewer disconnected
 * across a broadcast reconnects to silence), so consumers use this hook point
 * to reconcile against the server (re-fetch a snapshot / refresh the loader).
 */
export function subscribeToRoom<P extends RoomPath>(
  path: P,
  params: ParamsOf<P>,
  key: string,
  onEvent: (event: ServerEventOf<P>) => void,
  onReconnect?: () => void,
): () => void {
  let room = rooms.get(key);
  if (!room) {
    const socket = connectRoom(path, {
      params,
      reconnectDelayMs: RECONNECT_DELAY_MS,
    });
    const listeners = new Set<(event: unknown) => void>();
    const reconnectListeners = new Set<() => void>();
    const detachMessage = socket.on("message", (event) => {
      // `event` is ServerEventOf<P>; fan out to the type-erased listener set
      // (passing a typed value to (unknown)=>void is sound, no cast).
      for (const listener of [...listeners]) listener(event);
    });
    // VoidSocket re-dials internally on non-user closes, emitting "open" per
    // (re)connection. The first open is the initial connect; every later one
    // is a reconnect after a drop — exactly the gap with no replay.
    let openedOnce = false;
    const detachOpen = socket.on("open", () => {
      if (openedOnce) {
        for (const listener of [...reconnectListeners]) listener();
      }
      openedOnce = true;
    });
    room = {
      close: () => socket.close(),
      detach: () => {
        detachMessage();
        detachOpen();
      },
      listeners,
      reconnectListeners,
      refCount: 0,
    };
    rooms.set(key, room);
  }
  // The registry holds rooms of differing `P` in one Map, so listeners are
  // stored as (unknown)=>void. The socket for `path` only ever emits
  // ServerEventOf<P>, so re-narrowing the event for this subscriber is sound —
  // the single contained erasure (the public surface stays fully typed).
  // oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion -- the socket for `path` only emits ServerEventOf<P>; re-narrowing from the type-erased listener set is sound (see comment above)
  const fan = (event: unknown) => onEvent(event as ServerEventOf<P>);
  room.listeners.add(fan);
  if (onReconnect) room.reconnectListeners.add(onReconnect);
  room.refCount += 1;

  let released = false;
  return () => {
    if (released) return; // guard against double-invoke (StrictMode / re-runs)
    released = true;
    const current = rooms.get(key);
    if (!current) return;
    current.listeners.delete(fan);
    if (onReconnect) current.reconnectListeners.delete(onReconnect);
    current.refCount -= 1;
    if (current.refCount <= 0) {
      current.detach();
      current.close();
      rooms.delete(key);
    }
  };
}

/**
 * Subscribe to a `void/ws` room for the component's lifetime and forward each
 * server message to `onEvent`. Generic glue shared by every room consumer
 * (`useProjectRoom`, `useRunRoom`): the path resolves `P` against the generated
 * route map, so `params` and the `onEvent` event type are checked per-room with
 * no assertion at the call site. Connections are shared + ref-counted per room
 * (see `subscribeToRoom`), so any number of leaves on a page subscribing to the
 * same room hold ONE socket between them, auto-reconnecting (VoidSocket), torn
 * down when the last leaf unmounts.
 *
 * `onEvent` / `onReconnect` are read through refs so callers can pass a fresh
 * closure each render (e.g. one that closes over current props) without
 * re-opening the socket; the subscription is re-created only when `path` or
 * `params` change. `onReconnect` fires when the socket re-opens after a drop
 * (never the first open) — the hook point for missed-broadcast reconciliation,
 * since rooms have no event replay.
 */
export function useRoom<P extends RoomPath>(
  path: P,
  params: ParamsOf<P>,
  onEvent: (event: ServerEventOf<P>) => void,
  onReconnect?: () => void,
): void {
  const cb = useRef(onEvent);
  cb.current = onEvent;
  const reconnectCb = useRef(onReconnect);
  reconnectCb.current = onReconnect;

  // Stable dependency key — re-subscribe only when the target room changes.
  const key = `${path}|${JSON.stringify(params)}`;

  useEffect(() => {
    const stable = (event: ServerEventOf<P>) => cb.current(event);
    const stableReconnect = () => reconnectCb.current?.();
    return subscribeToRoom(path, params, key, stable, stableReconnect);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
}
